// <auto-generated />
using Economy.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Economy.Base.Persistence.Migrations.HotelDb
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20250501000636_InitHotelDbAppTechnicalSetting")]
    partial class InitHotelDbAppTechnicalSetting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppLanguage.AppLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRTL")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppLanguage");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppSettings.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomCss")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomJs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnableCDN")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableCache")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableDebugMode")
                        .HasColumnType("bit");

                    b.Property<bool>("ForceSSL")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSiteLive")
                        .HasColumnType("bit");

                    b.Property<string>("MaintenanceMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaticFileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppSettings.AppSettingTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppLanguageId")
                        .HasColumnType("int");

                    b.Property<int>("AppSettingId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MetaTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SiteTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AppLanguageId");

                    b.HasIndex("AppSettingId");

                    b.ToTable("AppSettingTranslation");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppSettings.AppTechnicalSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedIpAddresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomCss")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomJs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnableCDN")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableCache")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableCustomFooterScripts")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableCustomHeaderScripts")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableDebugMode")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableGlobalScriptInjection")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableMaintenanceIpWhitelist")
                        .HasColumnType("bit");

                    b.Property<bool>("EnablePreloader")
                        .HasColumnType("bit");

                    b.Property<string>("FacebookPixelCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ForceSSL")
                        .HasColumnType("bit");

                    b.Property<string>("GoogleAnalyticsCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSiteLive")
                        .HasColumnType("bit");

                    b.Property<string>("MaintenanceMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreloaderHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaticFileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppTechnicalSettings");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppSettings.AppSettingTranslation", b =>
                {
                    b.HasOne("Economy.Domain.Entites.EntityAppLanguage.AppLanguage", "AppLanguage")
                        .WithMany()
                        .HasForeignKey("AppLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Economy.Domain.Entites.EntityAppSettings.AppSetting", "AppSetting")
                        .WithMany("Translations")
                        .HasForeignKey("AppSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppLanguage");

                    b.Navigation("AppSetting");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppSettings.AppSetting", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
