// <auto-generated />
using Economy.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Economy.Base.Persistence.Migrations.HotelDb
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppLanguage.AppLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRTL")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AppLanguage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "tr",
                            Icon = "flag-icon flag-icon-tur",
                            IsActive = true,
                            IsDefault = true,
                            IsDeleted = false,
                            IsRTL = false,
                            Name = "Türkçe"
                        },
                        new
                        {
                            Id = 2,
                            Code = "en",
                            Icon = "flag-icon flag-icon-gbr",
                            IsActive = true,
                            IsDefault = false,
                            IsDeleted = false,
                            IsRTL = false,
                            Name = "English"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ar",
                            Icon = "flag-icon flag-icon-sau",
                            IsActive = true,
                            IsDefault = false,
                            IsDeleted = false,
                            IsRTL = true,
                            Name = "العربية"
                        });
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppSettings.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppSettings.AppSettingTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppLanguageId")
                        .HasColumnType("int");

                    b.Property<int>("AppSettingId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MetaTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SiteTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AppSettingId", "AppLanguageId")
                        .IsUnique();

                    b.ToTable("AppSettingTranslations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppLanguageId = 1,
                            AppSettingId = 1,
                            Description = "Site açıklaması Türkçe",
                            IsDeleted = false,
                            MetaDescription = "Meta açıklaması Türkçe",
                            MetaTitle = "Meta Başlık - TR",
                            SiteTitle = "Site Başlığı - TR"
                        },
                        new
                        {
                            Id = 2,
                            AppLanguageId = 2,
                            AppSettingId = 1,
                            Description = "Site description in English",
                            IsDeleted = false,
                            MetaDescription = "Meta description in English",
                            MetaTitle = "Meta Title - EN",
                            SiteTitle = "Site Title - EN"
                        });
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppSettings.AppTechnicalSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedIpAddresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomCss")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomJs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnableCDN")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableCache")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableCustomFooterScripts")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableCustomHeaderScripts")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableDebugMode")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableGlobalScriptInjection")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableMaintenanceIpWhitelist")
                        .HasColumnType("bit");

                    b.Property<bool>("EnablePreloader")
                        .HasColumnType("bit");

                    b.Property<string>("FacebookPixelCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ForceSSL")
                        .HasColumnType("bit");

                    b.Property<string>("GoogleAnalyticsCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSiteLive")
                        .HasColumnType("bit");

                    b.Property<string>("MaintenanceMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreloaderHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaticFileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppTechnicalSettings");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppSettings.AppSettingTranslation", b =>
                {
                    b.HasOne("Economy.Domain.Entites.EntityAppSettings.AppSetting", null)
                        .WithMany("Translations")
                        .HasForeignKey("AppSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppSettings.AppSetting", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
