<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Infrastructure\Economy.Persistence\Economy.Base.Persistence.csproj" />
    <ProjectReference Include="..\..\Economy.Application\Economy.Base.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dtos\UserDtos\" />
  </ItemGroup>

</Project>
