<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Dtos\UserDtos\**" />
    <EmbeddedResource Remove="Dtos\UserDtos\**" />
    <None Remove="Dtos\UserDtos\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Infrastructure\Economy.Persistence\Economy.Base.Persistence.csproj" />
    <ProjectReference Include="..\..\Economy.Application\Economy.Base.Application.csproj" />
  </ItemGroup>

</Project>
