// <auto-generated />
using System;
using Economy.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250410190438_FixedSeedData")]
    partial class FixedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppCategories.AppCategoryTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("AppLanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppCategoryId");

                    b.HasIndex("AppLanguageId");

                    b.ToTable("AppCategoryTranslation");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppContents.AppContents.AppContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ContentType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PublicationStatus")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AppCategoryId");

                    b.ToTable("AppContents", (string)null);
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppContents.AppContents.AppContentTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppContentId")
                        .HasColumnType("int");

                    b.Property<int>("AppLanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("AppContentId");

                    b.HasIndex("AppLanguageId");

                    b.ToTable("AppContentTranslations", (string)null);
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppLanguage.AppLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRTL")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AppLanguages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "tr",
                            Icon = "🇹🇷",
                            IsActive = true,
                            IsDefault = true,
                            IsDeleted = false,
                            IsRTL = false,
                            Name = "Türkçe"
                        },
                        new
                        {
                            Id = 2,
                            Code = "en",
                            Icon = "🇬🇧",
                            IsActive = true,
                            IsDefault = false,
                            IsDeleted = false,
                            IsRTL = false,
                            Name = "English"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ar",
                            Icon = "🇸🇦",
                            IsActive = true,
                            IsDefault = false,
                            IsDeleted = false,
                            IsRTL = true,
                            Name = "العربية"
                        });
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppMenus.AppMenuTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppLanguageId")
                        .HasColumnType("int");

                    b.Property<int>("AppMenuId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AppLanguageId");

                    b.HasIndex("AppMenuId");

                    b.ToTable("AppMenuTranslations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppLanguageId = 1,
                            AppMenuId = 1,
                            IsDeleted = false,
                            Title = "Ana Menü",
                            Url = "ana-menu"
                        },
                        new
                        {
                            Id = 2,
                            AppLanguageId = 2,
                            AppMenuId = 1,
                            IsDeleted = false,
                            Title = "Main Menu",
                            Url = "main-menu"
                        },
                        new
                        {
                            Id = 3,
                            AppLanguageId = 1,
                            AppMenuId = 2,
                            IsDeleted = false,
                            Title = "Odalar & Süitler",
                            Url = "odalar-suitler"
                        },
                        new
                        {
                            Id = 4,
                            AppLanguageId = 2,
                            AppMenuId = 2,
                            IsDeleted = false,
                            Title = "Rooms & Suites",
                            Url = "rooms-suites"
                        },
                        new
                        {
                            Id = 5,
                            AppLanguageId = 1,
                            AppMenuId = 3,
                            IsDeleted = false,
                            Title = "Restoran & Bar",
                            Url = "restoran-bar"
                        },
                        new
                        {
                            Id = 6,
                            AppLanguageId = 2,
                            AppMenuId = 3,
                            IsDeleted = false,
                            Title = "Restaurant & Bar",
                            Url = "restaurant-bar"
                        },
                        new
                        {
                            Id = 7,
                            AppLanguageId = 1,
                            AppMenuId = 4,
                            IsDeleted = false,
                            Title = "Spa & Wellness",
                            Url = "spa-wellness"
                        },
                        new
                        {
                            Id = 8,
                            AppLanguageId = 2,
                            AppMenuId = 4,
                            IsDeleted = false,
                            Title = "Spa & Wellness",
                            Url = "spa-wellness"
                        },
                        new
                        {
                            Id = 9,
                            AppLanguageId = 1,
                            AppMenuId = 5,
                            IsDeleted = false,
                            Title = "Hakkımızda",
                            Url = "hakkimizda"
                        },
                        new
                        {
                            Id = 10,
                            AppLanguageId = 2,
                            AppMenuId = 5,
                            IsDeleted = false,
                            Title = "About Us",
                            Url = "about-us"
                        },
                        new
                        {
                            Id = 11,
                            AppLanguageId = 1,
                            AppMenuId = 6,
                            IsDeleted = false,
                            Title = "İletişim",
                            Url = "iletisim"
                        },
                        new
                        {
                            Id = 12,
                            AppLanguageId = 2,
                            AppMenuId = 6,
                            IsDeleted = false,
                            Title = "Contact",
                            Url = "contact"
                        });
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppPages.AppPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHomePage")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AppPages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            IsHomePage = true
                        });
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppPages.AppPageSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppPageId")
                        .HasColumnType("int");

                    b.Property<int>("AppSectionId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppPageId");

                    b.HasIndex("AppSectionId");

                    b.ToTable("AppPageSections", (string)null);
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppPages.AppPageTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppLanguageId")
                        .HasColumnType("int");

                    b.Property<int>("AppPageId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppLanguageId");

                    b.HasIndex("AppPageId");

                    b.ToTable("AppPageTranslations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppLanguageId = 1,
                            AppPageId = 1,
                            Content = "Anasayfa",
                            IsDeleted = false,
                            MetaDescription = "Anasayfa",
                            MetaTitle = "Anasayfa",
                            Title = "Anasayfa",
                            Url = "anasayfa"
                        },
                        new
                        {
                            Id = 2,
                            AppLanguageId = 2,
                            AppPageId = 1,
                            Content = "Home",
                            IsDeleted = false,
                            MetaDescription = "Home",
                            MetaTitle = "Home",
                            Title = "Home",
                            Url = "home"
                        });
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppPages.AppSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SectionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AppSections", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "",
                            IsDeleted = false,
                            Name = "Anasayfa Slider",
                            SectionType = 2
                        },
                        new
                        {
                            Id = 2,
                            Content = "Doğanın nefes kesen güzelliğinin turkuaz sularla buluştuğu Kemer’ in kalbinde konumlanan Türkiz Resort Hotel göz alıcı mimarisi ve sıcak atmosferi ile sizi eşsiz bir mutluluğa davet ediyor.",
                            IsDeleted = false,
                            Name = "Imperial Turkiz Resort Hotel",
                            SectionType = 1
                        });
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppPages.AppSectionImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppSectionId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppSectionId");

                    b.ToTable("AppSectionImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppSectionId = 2,
                            Content = "",
                            IsDeleted = false,
                            Name = "Kurumsal 1",
                            Sequence = 1,
                            Thumbnail = "essiz-misafirperverligi-595bb.jpg"
                        },
                        new
                        {
                            Id = 2,
                            AppSectionId = 2,
                            Content = "",
                            IsDeleted = false,
                            Name = "Kurumsal 2",
                            Sequence = 2,
                            Thumbnail = "essiz-osmanli-stili-ve-misafirperverligi-7315a.jpg"
                        });
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppSettings.AppLogoSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MobileLogoPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WebLogoPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("AppLogoSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            MobileLogoPath = "img/logo_m.png",
                            WebLogoPath = "img/logo.png"
                        });
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppSettings.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomCss")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomJs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnableCDN")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableCache")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableDebugMode")
                        .HasColumnType("bit");

                    b.Property<bool>("ForceSSL")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSiteLive")
                        .HasColumnType("bit");

                    b.Property<string>("MaintenanceMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaticFileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppSettings.AppSettingTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppLanguageId")
                        .HasColumnType("int");

                    b.Property<int>("AppSettingId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MetaTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SiteTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AppLanguageId");

                    b.HasIndex("AppSettingId");

                    b.ToTable("AppSettingTranslations");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppSettings.AppTechnicalSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedIpAddresses")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomCss")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomJs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EnableCDN")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableCache")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableCustomFooterScripts")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableCustomHeaderScripts")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableDebugMode")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableGlobalScriptInjection")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableMaintenanceIpWhitelist")
                        .HasColumnType("bit");

                    b.Property<bool>("EnablePreloader")
                        .HasColumnType("bit");

                    b.Property<string>("FacebookPixelCode")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("ForceSSL")
                        .HasColumnType("bit");

                    b.Property<string>("GoogleAnalyticsCode")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSiteLive")
                        .HasColumnType("bit");

                    b.Property<string>("MaintenanceMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PreloaderHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaticFileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("AppTechnicalSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppVersion = "v1.0.0",
                            CustomCss = "",
                            CustomJs = "",
                            DomainName = "www.otelsitem.com",
                            EnableCDN = false,
                            EnableCache = true,
                            EnableCustomFooterScripts = false,
                            EnableCustomHeaderScripts = false,
                            EnableDebugMode = false,
                            EnableGlobalScriptInjection = false,
                            EnableMaintenanceIpWhitelist = false,
                            EnablePreloader = false,
                            ForceSSL = true,
                            IsDeleted = false,
                            IsSiteLive = true,
                            MaintenanceMessage = "Sitemiz şu anda bakım modundadır. Lütfen daha sonra tekrar deneyiniz.",
                            StaticFileUrl = ""
                        });
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppUsers.AppUserRefreshToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserRefreshTokens", (string)null);
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityCategories.AppCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContentType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("PublicationStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("AppCategories");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityMenuItems.AppMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentMenuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentMenuId");

                    b.ToTable("AppMenus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            IsExternal = false
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            IsExternal = false
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            IsExternal = false
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            IsExternal = false
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            IsExternal = false
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            IsExternal = false
                        });
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntitySlides.AppSlide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppSectionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppSlides", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppSectionId = 1,
                            IsDeleted = false,
                            Sequence = 1,
                            Thumbnail = "slide_1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            AppSectionId = 1,
                            IsDeleted = false,
                            Sequence = 1,
                            Thumbnail = "slide_2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            AppSectionId = 1,
                            IsDeleted = false,
                            Sequence = 1,
                            Thumbnail = "slide_3.jpg"
                        });
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntitySlides.AppSlideTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppLanguageId")
                        .HasColumnType("int");

                    b.Property<int>("AppSlideId")
                        .HasColumnType("int");

                    b.Property<string>("ButtonIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppLanguageId");

                    b.HasIndex("AppSlideId");

                    b.ToTable("AppSlideTranslations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppLanguageId = 1,
                            AppSlideId = 1,
                            ButtonIcon = "fa-search",
                            ButtonText = "Keşfet",
                            ButtonUrl = "/explore",
                            Content = "En iyi tatil deneyimi için bizimle olun.",
                            IsDeleted = false,
                            IsExternal = false,
                            Title = "Hoş Geldiniz"
                        },
                        new
                        {
                            Id = 2,
                            AppLanguageId = 2,
                            AppSlideId = 1,
                            ButtonIcon = "fa-search",
                            ButtonText = "Explore",
                            ButtonUrl = "/explore",
                            Content = "Join us for the best vacation experience.",
                            IsDeleted = false,
                            IsExternal = false,
                            Title = "Welcome"
                        },
                        new
                        {
                            Id = 3,
                            AppLanguageId = 1,
                            AppSlideId = 2,
                            ButtonIcon = "fa-search",
                            ButtonText = "Keşfet",
                            ButtonUrl = "/explore",
                            Content = "En iyi tatil deneyimi için bizimle olun.",
                            IsDeleted = false,
                            IsExternal = false,
                            Title = "Hoş Geldiniz"
                        },
                        new
                        {
                            Id = 4,
                            AppLanguageId = 2,
                            AppSlideId = 2,
                            ButtonIcon = "fa-search",
                            ButtonText = "Explore",
                            ButtonUrl = "/explore",
                            Content = "Join us for the best vacation experience.",
                            IsDeleted = false,
                            IsExternal = false,
                            Title = "Welcome"
                        },
                        new
                        {
                            Id = 5,
                            AppLanguageId = 1,
                            AppSlideId = 3,
                            ButtonIcon = "fa-search",
                            ButtonText = "Keşfet",
                            ButtonUrl = "/explore",
                            Content = "En iyi tatil deneyimi için bizimle olun.",
                            IsDeleted = false,
                            IsExternal = false,
                            Title = "Hoş Geldiniz"
                        },
                        new
                        {
                            Id = 6,
                            AppLanguageId = 2,
                            AppSlideId = 3,
                            ButtonIcon = "fa-search",
                            ButtonText = "Explore",
                            ButtonUrl = "/explore",
                            Content = "Join us for the best vacation experience.",
                            IsDeleted = false,
                            IsExternal = false,
                            Title = "Welcome"
                        });
                });

            modelBuilder.Entity("Economy.Domain.Entites.Identities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AppRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "a1111111-b222-c333-d444-e55555555555",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Economy.Domain.Entites.Identities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefaultAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AppUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "33333333-dddd-eeee-ffff-444444444444",
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            FirstName = "Sistem",
                            IsDefaultAdmin = true,
                            LastName = "Yöneticisi",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEGCzY20L2G+TswPL8nVZ7gCm+3OaKjk9iN9abVdTOf5wjMPVnljfMRZsWYixI4LSQg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "11111111-aaaa-bbbb-cccc-222222222222",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Economy.Domain.Entities.Identity.AppRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Economy.Domain.Entities.Identity.AppUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Economy.Domain.Entities.Identity.AppUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Economy.Domain.Entities.Identity.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Economy.Domain.Entities.Identity.AppUserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppCategories.AppCategoryTranslation", b =>
                {
                    b.HasOne("Economy.Domain.Entites.EntityCategories.AppCategory", null)
                        .WithMany("Translations")
                        .HasForeignKey("AppCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Economy.Domain.Entites.EntityAppLanguage.AppLanguage", "AppLanguage")
                        .WithMany()
                        .HasForeignKey("AppLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppLanguage");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppContents.AppContents.AppContent", b =>
                {
                    b.HasOne("Economy.Domain.Entites.EntityCategories.AppCategory", "AppCategory")
                        .WithMany()
                        .HasForeignKey("AppCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppCategory");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppContents.AppContents.AppContentTranslation", b =>
                {
                    b.HasOne("Economy.Domain.Entites.EntityAppContents.AppContents.AppContent", null)
                        .WithMany("Translations")
                        .HasForeignKey("AppContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Economy.Domain.Entites.EntityAppLanguage.AppLanguage", "AppLanguage")
                        .WithMany()
                        .HasForeignKey("AppLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppLanguage");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppMenus.AppMenuTranslation", b =>
                {
                    b.HasOne("Economy.Domain.Entites.EntityAppLanguage.AppLanguage", "AppLanguage")
                        .WithMany()
                        .HasForeignKey("AppLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Economy.Domain.Entites.EntityMenuItems.AppMenu", null)
                        .WithMany("Translations")
                        .HasForeignKey("AppMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppLanguage");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppPages.AppPageSection", b =>
                {
                    b.HasOne("Economy.Domain.Entites.EntityAppPages.AppPage", "AppPage")
                        .WithMany("AppPageSections")
                        .HasForeignKey("AppPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Economy.Domain.Entites.EntityAppPages.AppSection", "AppSection")
                        .WithMany("AppPageSections")
                        .HasForeignKey("AppSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppPage");

                    b.Navigation("AppSection");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppPages.AppPageTranslation", b =>
                {
                    b.HasOne("Economy.Domain.Entites.EntityAppLanguage.AppLanguage", "AppLanguage")
                        .WithMany()
                        .HasForeignKey("AppLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Economy.Domain.Entites.EntityAppPages.AppPage", null)
                        .WithMany("Translations")
                        .HasForeignKey("AppPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppLanguage");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppPages.AppSectionImage", b =>
                {
                    b.HasOne("Economy.Domain.Entites.EntityAppPages.AppSection", "AppSection")
                        .WithMany("AppSectionImages")
                        .HasForeignKey("AppSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppSection");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppSettings.AppSettingTranslation", b =>
                {
                    b.HasOne("Economy.Domain.Entites.EntityAppLanguage.AppLanguage", "AppLanguage")
                        .WithMany()
                        .HasForeignKey("AppLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Economy.Domain.Entites.EntityAppSettings.AppSetting", "AppSetting")
                        .WithMany("Translations")
                        .HasForeignKey("AppSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppLanguage");

                    b.Navigation("AppSetting");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityCategories.AppCategory", b =>
                {
                    b.HasOne("Economy.Domain.Entites.EntityCategories.AppCategory", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityMenuItems.AppMenu", b =>
                {
                    b.HasOne("Economy.Domain.Entites.EntityMenuItems.AppMenu", "ParentMenu")
                        .WithMany("SubMenus")
                        .HasForeignKey("ParentMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentMenu");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntitySlides.AppSlideTranslation", b =>
                {
                    b.HasOne("Economy.Domain.Entites.EntityAppLanguage.AppLanguage", "AppLanguage")
                        .WithMany()
                        .HasForeignKey("AppLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Economy.Domain.Entites.EntitySlides.AppSlide", null)
                        .WithMany("Translations")
                        .HasForeignKey("AppSlideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppLanguage");
                });

            modelBuilder.Entity("Economy.Domain.Entities.Identity.AppRoleClaim", b =>
                {
                    b.HasOne("Economy.Domain.Entites.Identities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Economy.Domain.Entities.Identity.AppUserClaim", b =>
                {
                    b.HasOne("Economy.Domain.Entites.Identities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Economy.Domain.Entities.Identity.AppUserLogin", b =>
                {
                    b.HasOne("Economy.Domain.Entites.Identities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Economy.Domain.Entities.Identity.AppUserRole", b =>
                {
                    b.HasOne("Economy.Domain.Entites.Identities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Economy.Domain.Entites.Identities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Economy.Domain.Entities.Identity.AppUserToken", b =>
                {
                    b.HasOne("Economy.Domain.Entites.Identities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppContents.AppContents.AppContent", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppPages.AppPage", b =>
                {
                    b.Navigation("AppPageSections");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppPages.AppSection", b =>
                {
                    b.Navigation("AppPageSections");

                    b.Navigation("AppSectionImages");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityAppSettings.AppSetting", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityCategories.AppCategory", b =>
                {
                    b.Navigation("SubCategories");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntityMenuItems.AppMenu", b =>
                {
                    b.Navigation("SubMenus");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Economy.Domain.Entites.EntitySlides.AppSlide", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
