<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspectCore.Abstractions" Version="2.4.0" />
    <PackageReference Include="Autofac" Version="8.2.0" />
    <PackageReference Include="Autofac.Extras.DynamicProxy" Version="7.1.0" />
    <PackageReference Include="Castle.Core" Version="5.2.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="9.0.3" />
  </ItemGroup>

</Project>
