<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Economy.Core\Economy.Core.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Economy.Persistence\Economy.Base.Persistence.csproj" />
    <ProjectReference Include="..\Economy.PanelUI\Economy.Panel.UI.csproj" />
  </ItemGroup>

</Project>
